apiVersion: batch/v1
kind: Job
metadata:
  name: cluster-post-shrink
  labels:
    app: tigergraph
spec:
  template:
    metadata:
      labels:
        app: tigergraph
    spec:
      serviceAccountName: tigergraph-installer
      initContainers:
      - name: init-cluster-post-shrink
        image: tigergraph/tigergraph-k8s-installer:3.5.0
        env:
        - name: POD_PREFIX
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: pod.prefix
        command: 
        - "/bin/sh"
        - "-c"
        - >
          set -e;
          kubectl rollout status --watch --timeout=2h statefulset ${POD_PREFIX};
          sleep 5;
      containers:
      - name: cluster-post-shrink
        image: tigergraph/tigergraph-k8s-installer:3.5.0
        env:
        - name: CLUSTER_SIZE
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: cluster_size
        - name: SERVICE_NAME
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: service.headless.name
        - name: POD_PREFIX
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: pod.prefix
        - name: NAMESPACE
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: namespace
        command:
        - "/bin/sh"
        - "-c"
        - |
          export SSHPASS='tigergraph';
          for i in `seq 0 $(($CLUSTER_SIZE-1))`
          do
            sshpass -e ssh -o StrictHostKeyChecking=no tigergraph@${POD_PREFIX}-${i}.${SERVICE_NAME}.${NAMESPACE} "
              set -e;
              export PATH=$PATH:/home/tigergraph/tigergraph/app/cmd:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin;
              find /home/tigergraph/tigergraph/data -regex \"/home/tigergraph/tigergraph/data/expansion-export-.*\" -delete;
              find /home/tigergraph/tigergraph/data -regex \"/home/tigergraph/tigergraph/data/.*-pre-expand-backup-.*\" -delete
            "
          done
      restartPolicy: Never
  backoffLimit: 0
